Repository openshift-eng/ci-test-mapping, pull requests merged in 2025-04, with the labels that each got.

#250 Fix mapping verify command
  cmd/ci-test-mapping/mapping_verify.go
Labels: lgtm, approved

#256 trt-2049: rename watch channels
  pkg/components/kubeapiserver/component.go
Labels: lgtm, approved, jira/valid-reference

#261 NO-JIRA: bump linter
  Dockerfile.buildroot
  hack/go-lint.sh
  pkg/bigquery/client.go
  pkg/components/component_test.go
Labels: lgtm, approved, jira/valid-reference

#257 update correct mapping for management console and baremetal
  pkg/components/baremetalhardwareprovisioning/baremetaloperator/component.go
  pkg/components/managementconsole/component.go
Labels: lgtm, approved, ok-to-test

#213 update monitoring mappings: Monitoring/Grafana jira component will be removed
  pkg/components/monitoring/grafana/capabilities.go
  pkg/components/monitoring/grafana/component.go
  pkg/registry/registry.go
Labels: lgtm, approved, ok-to-test

#260 Rename `MetricsCollectionProfiles` tests to reflect serialization
  pkg/components/monitoring/component.go
Labels: lgtm, approved, ok-to-test
